version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gymapp-backend
    ports:
      - "8081:8081"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    networks:
      - gymapp-network

networks:
  gymapp-network:
    driver: bridge 