[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -jar target/backend-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on-failure"

[deploy.env]
PORT = "8080"
JAVA_OPTS = "-Xms512m -Xmx1024m -XX:+UseG1GC"