[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -jar target/backend-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"  # Note the underscore instead of hyphen

[deploy.env]
PORT = "8080"
JAVA_OPTS = "-Xms512m -Xmx1024m -XX:+UseG1GC"
SPRING_DATASOURCE_URL = "jdbc:mysql://switchyard.proxy.rlwy.net:41729/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=30000&socketTimeout=60000"
SPRING_DATASOURCE_USERNAME = "root"
SPRING_DATASOURCE_PASSWORD = "MGsAeHEsjYPCtbYDiBNwfQhwDJXQBQyF"