[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"

[deploy.env]
JAVA_OPTS = "-Xms512m -Xmx1024m -XX:+UseG1GC -Dspring.profiles.active=prod"
SPRING_DATASOURCE_URL = "jdbc:mysql://switchyard.proxy.rlwy.net:41729/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
SPRING_DATASOURCE_USERNAME = "root"
SPRING_DATASOURCE_PASSWORD = "MGsAeHEsjYPCtbYDiBNwfQhwDJXQBQyF"
SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT = "org.hibernate.dialect.MySQLDialect"









